// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
    export interface GlobalComponents {
        // CustomNomore: typeof import('./src/components/custom-nomore/custom-nomore.vue')['default']
        // CustomRefresher: typeof import('./src/components/custom-refresher/custom-refresher.vue')['default']
        // DropDownDemo: typeof import('./src/components/drop-down-demo/drop-down-demo.vue')['default']
        // LzcPicker: typeof import('./src/components/lzc-picker/lzc-picker.vue')['default']
        // PreviewImages: typeof import('./src/components/preview-images/preview-images.vue')['default']
        // SelectCy: typeof import('./src/components/select-cy/select-cy.vue')['default']
        // SwiperListItem: typeof import('./src/components/swiper-list-item/swiper-list-item.vue')['default']
        // SwiperTabsPaging: typeof import('./src/components/swiper-tabs-paging/swiper-tabs-paging.vue')['default']
        // SwiperTabsPagingDemo: typeof import('./src/components/swiper-tabs-paging-demo/swiper-tabs-paging-demo.vue')['default']
        // UniFormsForms: typeof import('./src/components/uni-forms-forms/uni-forms-forms.vue')['default']
        // UploadVideo: typeof import('./src/components/upload-video/upload-video.vue')['default']
        // WybPopup: typeof import('./src/components/lzc-picker/wyb-popup.vue')['default']
    }
}

export {}
